### PR TITLE
refactor: bootstrapping typescript

### PR DESCRIPTION
**Pull request by KnisterPeter**

### CODE REVIEW

**Comment by HannesRakete** [comment]
What is the intention here?
Why Typescript?
Editor-Settings in repo?!

**Comment by KnisterPeter** [comment]
I've bootstraped the repo to typescript because @ZauberNerd asked me to do so.
The AWS-SDK package has typings provided by amazon and therefore this might be a natural fit. :wink: 

The editor-settings where there before.

**Comment by ZauberNerd** [comment]
@HannesRakete I asked @KnisterPeter to bootstrap a typescript implementation, because the `aws-sdk` has typings for typescript but not flowtype: https://github.com/aws/aws-sdk-js/tree/master/ts

**Comment by KnisterPeter** [comment]
Oh, I guess me do not mean the editor settings but the settings for vscode?
They are not tied to a platform and could be shared easily. If you don't like them here I could remove and ignore them but every person using vscode has to reconfigure its IDE then.

**Comment by KnisterPeter** [comment]
And sorry, I should have explained the purpose in the PR desccription above. :smile:

**Comment by HannesRakete** [comment]
Thx!

**Pull request merged**
